/** Approved raid boss mob names (lowercase). Only records matching these are
 *  served by the GET endpoints and retained by the DELETE purge operation. */
export const ALLOWED_MOBS = [
  // Classic
  'lord nagafen', 'lady vox',
  'cazic thule', 'dread', 'fright', 'terror',
  'innoruuk',
  'thunder spirit princess', 'noble dojorn', 'protector of sky', 'gorgalosk',
  'keeper of souls', 'overseer of air',
  'spiroc guardian', 'the spiroc lord',
  'bazzt zzzt',
  'sister of the spire',
  'hand of veeshan', 'eye of veeshan',
  // Kunark
  'severilous', 'talendor', 'faydedar', 'gorenaire', 'trakanon',
  'venril sathir',
  'king tearis thex', "queen velazul di'zok",
  'silverwing', 'hoshkar', 'phara dar', 'nexona', 'druushk', 'xygoz',
  // Velious
  'dain frostreaver iv',
  'klandicar', 'sontalak',
  'zlandicar',
  'derakor the vindicator', 'statue of rallos zek', 'king tormax',
  'lord yelinak',
  'velketor the sorcerer',
  'tunare',
  'wuoshi', 'lord doljonijiarnimorinar',
  'hraashna', 'nanzata', 'tukaarak', 'ventani',
  'the progenitor', 'master of the guard', 'the final arbiter', 'kerafyrm',
  'zeixshi-kar', 'tjudawos', 'vyskudra', 'kildrukaun the ancients',
  'casalem', 'essedera', 'grozzmel', 'krigara', 'lepethida',
  'midayor', 'tavekalem', 'ymmeln', 'zemm',
  'aaryonar', 'dozekar the cursed', 'cekenar', 'lord feshlak', 'jorlleag',
  "lord koi'doken", 'lord kreizenn', 'lendiniara the keeper',
  'lady mirenilla', 'lady nevederia', 'sevalak', 'lord vyemm',
  'dagarn the destroyer', 'zlexak', 'eashen of the sky',
  'ikatiar the venom', 'gozzrem', 'telkorenar', 'vulak`aerr',
  // Luclin
  'xerikizh the creator', 'the high priest of ssraeshza', 'emperor ssraeshza',
  'a glyph covered serpent', 'vyzh`dra the exiled', 'vyzh`dra the cursed',
  'lord inquisitor seru',
  'khati sha the twisted',
  'the itraer vius', 'shei vinitras', 'the insanity crawler',
  'grieg veneficus',
  'kaas thox xi ans dyek',
  'diabo xi xin', 'diabo xi va', 'diabo xi xin thall', 'thall va kelun',
  'diabo xi va terminiel', 'thunderos xi diabo',
  'va xi aten ha ra', 'aten ha ra',
]
